version: '3.8'

services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/home/podcast-archive
    environment:
      - CHROMADB_DB_PATH=/home/chroma_db
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  chroma_db: