services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./chroma_db:/app/chroma_db
    environment:
      - CHROMADB_DB_PATH=/app/chroma_db
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload