# Import the config module
from config import REPO_ROOT, GITHUB_USERNAME, GITHUB_TOKEN, GITHUB_REPO_NAME, PODCAST_AUDIO_FOLDER, TRANSCRIBED_FOLDER, PODCAST_HISTORY_FILE

print(f"{REPO_ROOT},{GITHUB_USERNAME},{GITHUB_TOKEN},{GITHUB_REPO_NAME},{PODCAST_AUDIO_FOLDER},{TRANSCRIBED_FOLDER},{PODCAST_HISTORY_FILE}")
